version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: review_predictor_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: review_predictor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=vector

volumes:
  postgres_data:

